spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
  jpa:
    properties:
      hibernate:
        default_schema: chess_tournament
    open-in-view: false
  flyway:
    schemas: chess_tournament
